apiVersion: apps/v1
kind: Deployment
metadata:
  name: roguelearn-event-api
  labels:
    app: roguelearn-event-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: roguelearn-event-api
  template:
    metadata:
      labels:
        app: roguelearn-event-api
        component: backend
    spec:
      containers:
        - name: event
          image: songphuc/event:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080 # receive here
              protocol: TCP
            - containerPort: 443
              name: https
            - name: grpc
              containerPort: 50051 # receive here
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080 # HTTP Port
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080 # HTTP Port
            initialDelaySeconds: 5
            periodSeconds: 5
