apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: roguelearn

resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml

images:
  - name: songphuc/executor
    newTag: v1.0.0
