apiVersion: v1
kind: Service
metadata:
  name: executor-service
  labels:
    app: roguelearn-app
    component: backend
spec:
  type: ClusterIP
  selector:
    app: roguelearn-executor-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080 # forward to here
    - name: grpc
      protocol: TCP
      port: 50051 # Common Port for gRPC
      targetPort: 50051 # forward to here
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
