apiVersion: v1
kind: Service
metadata:
  name: executor-service
  labels:
    app: roguelearn-app
    component: backend
spec:
  type: NodePort
  selector:
    app: executor
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081 # forward to here
      nodePort: 30010
    - name: grpc
      protocol: TCP
      port: 8082
      targetPort: 8082 # forward to here
      nodePort: 30011
